# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PlayingCard' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlayingCard

  target 'PlayingCardTests' do
    inherit! :search_paths
    # Pods for testing
    pod "Cuckoo"
  end

  target 'PlayingCardUITests' do
    # Pods for testing
  end

end
